### ISSUE TITLE
Prop.Correct.Cued 

### ISSUE THREAD

**Issue by jgeller112** [npm27/lrd#2]
Hi, 

I am having some issues with prop.correct.cued. It works with the sample data, but not my data. 

Overall, It does not seem flexible for most purposes. Why do individuals have to provide both trial ids and subject ids? I have an experiment where each P gets the same cue-targets. 

```
scored_output <- lrd::prop_correct_cued(data = dataset1,
                                   responses = "textbox.text",
                                   key = "target",
                                   key.trial = "rowid",
                                   id = "participant",
                                   id.trial = "rowid",
                                   cutoff = 3,
                                   flag = TRUE, group.by = "font")
```
```
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
```

**Comment by jgeller112** [comment]
@doomlab Do you have an answer?

**Comment by jgeller112** [comment]
The shiny application gives me what I want but I would like to be able to make it reproducible in R.  

Also, it seems the shiny app uses percent overlap whereas the R package uses distance?

**Comment by doomlab** [comment]
@jgeller112 apologies - I don't know why I didn't get the notification in December. Do you have a mini version of your data for me to test what the issue is? 

I also don't know if @npm27 has updated the online shiny version - it was based on the old code, but the new version is embedded into the package, so it's got the newer code. I'll see if I can compare, as I also rewrote some of the outputs.

```
Why do individuals have to provide both trial ids and subject ids? 
I have an experiment where each P gets the same cue-targets.
```
The purpose here is if your key is not embedded into the data already. For example, if you had a trial number in your data with participant responses, but then the trial number to correct answer was stored in a different place. If you happen to have the data with both already embedded, you would do what you did here.

**Comment by jgeller112** [comment]
@doomlab Thanks for looking into this :)

Here is link to a file: 

https://github.com/jgeller112/SF-Testing/blob/master/TimeTaskSelf/Summary_Data/Cued%20Recall/test.csv

**Comment by jgeller112** [comment]
Hi @doomlab!

I figured out the problem and finally got it to work. 

I had to add a unique trial_id for each row.
